"""Shared Quiet Forensics site parts are copies - edit the original, not this project.

GENERATED by security-biz/qf-common/qf_sync.py - do not edit here. The original of every file under
site/shared/, of every <!-- qf:... --> region and of the shared Python package lives in qf-common; change it there and run
`python qf_sync.py sync`. This test only compares against shared.lock.json, so it runs without
qf-common (CI and Cloud Build see this project alone).
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

import pytest

PROJECT = Path(__file__).resolve().parents[1]
LOCK = PROJECT / "shared.lock.json"
FIX = "is a synced copy from qf-common: edit security-biz/qf-common and run `python qf_sync.py sync`"


def _digest(data: bytes) -> str:
    return hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()


def _lock() -> dict:
    if not LOCK.is_file():
        pytest.skip("no shared.lock.json - this project does not use qf-common yet")
    return json.loads(LOCK.read_text(encoding="utf-8"))


def test_shared_files_are_unedited_copies():
    lock = _lock()
    if "files" not in lock:
        pytest.skip("this project takes no shared site files")
    shared = PROJECT / lock["shared_dir"]
    bad = [n for n, h in lock["files"].items() if not (shared / n).is_file() or _digest((shared / n).read_bytes()) != h]
    assert not bad, f"{bad} {FIX}"


def test_shared_regions_in_pages_are_unedited():
    lock = _lock()
    site = PROJECT / "site"
    bad = []
    for page, regions in lock.get("regions", {}).items():
        text = (site / page).read_bytes().decode("utf-8").replace("\r\n", "\n")
        found = {m.group(1): _digest(m.group(2).encode("utf-8"))
                 for m in re.finditer(r"<!--\s*qf:([a-z]+)[^>]*-->\n?(.*?)<!--\s*/qf:\1\s*-->", text, re.DOTALL)}
        bad += [f"{page}#{name}" for name, h in regions.items() if found.get(name) != h]
    assert not bad, f"{bad} {FIX}"


def test_shared_python_modules_are_unedited_copies():
    lock = _lock()
    if "python" not in lock:
        pytest.skip("this project takes no shared Python modules")
    pydir = PROJECT / lock["python_dir"]
    bad = [n for n, h in lock["python"].items() if not (pydir / n).is_file() or _digest((pydir / n).read_bytes()) != h]
    assert not bad, f"{bad} {FIX}"
